ejercicios JS semana 5
undefined-academy/semana-5 pull request #11
Opened 2023-04-24 22:20 UTC by equiman

Gracias por revisar mis ejercicios. Estos son los pasos que realice.

- Hice fork al repositorio
- Adicione respuesta del ejercicio de clases con propiedades privadas
- Adicione ejercicio de llamado asíncrono
- Adicione contador 
- Adicione contador con closure
- Adicione ejercicio de validación de correos
- Realice algunas simulaciones de pruebas unitarias usando console.assert

2023-04-25 04:33 UTC, Alexis033 requested changes
Genial, no sabía lo del console.assert() muy genial ver cómo funciona. Veo todo bien excepto el countToVar.js que me da todos los números de una, te hice la sugerencia de los cambios que creo solucionarían el problema.

2023-04-25 04:33 UTC, Alexis033 commented on exercises/equiman-0343/countTo10Var.js
> +        setTimeout(() => {
Hola yo diría que en el setTimeout no necesitas volver a definir la función y puedes poner directamente setTimeout(print, number*SEC_IN_MS)

2023-04-25 04:33 UTC, Alexis033 commented on exercises/equiman-0343/countTo10Var.js
> +        return () => console.log(number)
y este return sería innecesario.

2023-04-25 04:33 UTC, Alexis033 commented on exercises/equiman-0343/countTo10Var.js
> +        timer(i)()
y aquí pues ya no sería necesario los segundo () porque se llamaría directo a la función.

2023-04-25 07:43 UTC, equiman commented
> Veo todo bien excepto el countToVar.js que me da todos los números de una, te hice la sugerencia de los cambios que creo solucionarían el problema.

Gracias por la revision y los comentarios, mañana le doy una revisada que cuando hice la prueba me hizo el conteo bien, pero igual voy a ver los otros comentarios. Gracias

2023-04-25 15:07 UTC, equiman commented
A proposito. Esta extension tambien ayuda bastante para escribir los `console...` y tambien para hacer debug de CSS.

https://marketplace.visualstudio.com/items?itemName=deinsoftware.debug-snippets

2023-04-25 20:46 UTC, equiman commented
Listo @Alexis033 ya quedaron. Muchas gracias, entendí mejor los closures.

2023-04-25 21:03 UTC, Alexis033 approved these changes
Genial, si puedes echarle un ojito a la mía no me quejo jajaja
[Link PR](https://github.com/undefined-academy/semana-5/pull/12)

2023-04-25 21:15 UTC, INGCapaDev requested changes
Buenas Equiman, muy interesante tu trabajo aprendi algunas cosas nuevas, el unico detalle que encontre es que en el trabajo de email te faltaria que quitara el subaddresing de los emails, en el de countTo10Var no me los imprime por consola al menos que cambie el `console.time` por un `console.log` , y por ultimo en el metodo estatico de Student como recomendacion le puedes pasar un objeto y de ahi sacar los values del firstname y el lastname en vez de dejarlos por defecto como string, excelente trabajo me ayudo a comprender cosas nuevas saludos bro 🥰👍⭐

2023-04-25 21:16 UTC, INGCapaDev commented
Cuando realizes los cambios me solicitas el re-review te agradeceria si pudieras revisar el mio, claro solo si tienes el tiempo, saludos te dejo el enlace por aqui: https://github.com/undefined-academy/semana-5/pull/19

2023-04-25 21:27 UTC, equiman commented
> el unico detalle que encontre es que en el trabajo de email te faltaria que quitara el subaddresing de los emails

Ese punto lo hago en la línea 6, te adjunto imagen con el resultado de la consola

![image](https://user-images.githubusercontent.com/933393/234407848-0d7d8426-6fd4-4e24-b207-2a42a7eae24d.png)

2023-04-25 21:27 UTC, equiman commented
> en el de countTo10Var no me los imprime por consola al menos que cambie el `console.time` por un `console.log` 

corregido

2023-04-25 21:33 UTC, INGCapaDev commented
@equiman una disculpa error mio lo del subaddressing tenia una idea errorea pensaba que con el subadressing se referia por ejemplo : correo@example.com.uk el ".uk"

2023-04-25 21:36 UTC, equiman commented
> y por ultimo en el metodo estatico de Student como recomendacion le puedes pasar un objeto y de ahi sacar los values del firstname y el lastname en vez de dejarlos por defecto como string

listo modificado y corregido

2023-04-25 21:36 UTC, INGCapaDev approved these changes

2023-04-25 21:37 UTC, INGCapaDev commented
Listo @equiman  perdon por el error del subadressing, muy buen trabajo aprendi cosas nuevas como lo del `console.table`

2023-04-25 21:38 UTC, equiman commented
> @equiman una disculpa error mio lo del subaddressing tenia una idea errorea pensaba que con el subadressing se referia por ejemplo : [correo@example.com.uk](mailto:correo@example.com.uk) el ".uk"

no problem mejor aclarar.

> Cuando realizes los cambios me solicitas el re-review te agradeceria si pudieras revisar el mio, claro solo si tienes el tiempo, saludos te dejo el enlace por aqui: #19

listolis ya quedaron los cambios, le voy a dar un mirada a tu PR

Muchas gracias.

2023-04-26 00:22 UTC, merged

2023-04-30 13:40 UTC, DevOld112 reviewed
Se que el PR ya esta cerrado pero que increible como escribiste todo el codigo en general pero me impresiono que en `student.js` devuelva todo en unas tablas muy bonito y organizado, desconocia que se podia hacer eso.

Felicidades.

2023-04-30 13:55 UTC, equiman commented
Muchas gracias @DevOld112 asi entre los aportes de todos vamos aprendiendo un poco mas cada día