Semana-5
undefined-academy/semana-5 pull request #13
Opened 2023-04-25 04:22 UTC by facu1391

1. Se creo una class Student, con un respectivo get y un metodo static fromObject.
2. Se creo una funcion que cuenta del 1 al 10, imprimiendo un numero por cada segundo.
3. Se modifico la funcion de conteo, intercambiando la variable declarada con let por var.
4. Se creo una funcion que filtra una lista de mails, y les remueve el subadressing.

2023-04-25 05:10 UTC, JoseCamilo84 approved these changes

2023-04-25 05:11 UTC, JoseCamilo84 commented
Me revisarías mi PR también?

2023-04-25 06:38 UTC, facu1391 commented
Si con mucho gusto ya lo hago.

2023-04-26 21:33 UTC, andrealvarez2d approved these changes
Muy bien, el código es fácil de leer

2023-04-26 22:08 UTC, MauBedoya requested changes
mmm me parece que algunos de los ejercicios no están funcionando como deberían, te deje unos comentarios en esos que revise, dales una mirada y avisas que tal...

2023-04-26 22:08 UTC, MauBedoya commented on exercises/facundo91-1495/emailValidator.js
> +const emailRegex =  /^[\W.-]+(\+[\W.-]+)?@[\W-]+\.[\W]{2,7}$/
mmm parece que te confundiste en la expresión regular, "\w" busca caracteres alfanuméricos latinos, pero al usar "\W" estas buscando el contrario, por lo que no toma validos correos que si debería

2023-04-26 22:08 UTC, MauBedoya commented on exercises/facundo91-1495/emailValidator.js
> +    "AnimationPlaybackEvent.smith+work@example.co.uk",
aquí me parece que se tenía que tomar como validos los correos con dominios de segundo nivel, tercer y niveles superiores 🤔

2023-04-26 22:08 UTC, MauBedoya commented on exercises/facundo91-1495/Student.js
> +    average.array.forEach(({fullName, average}) => {
al ejecutar tu código me salta un error en esta línea
![image](https://user-images.githubusercontent.com/111880575/234713341-ebc16394-04d8-446e-a575-74d1eda2dbba.png)

me parece que debería ser:
```js
average.forEach......
```
sin el "array."

2023-04-27 00:12 UTC, facu1391 commented on exercises/facundo91-1495/emailValidator.js
> +const emailRegex =  /^[\W.-]+(\+[\W.-]+)?@[\W-]+\.[\W]{2,7}$/
Si tienes razón! ya será modificado, muchas gracias por la corrección.

2023-04-27 00:14 UTC, facu1391 commented on exercises/facundo91-1495/Student.js
> +    average.array.forEach(({fullName, average}) => {
Perfecto! muchas gracias por la corrección, ya será modificado

2023-04-27 19:05 UTC, MauBedoya approved these changes
Genial, ya estan corregidos los detalles importantes 👍

2023-04-28 09:29 UTC, merged