agregar los cuatro ejercicios de la semana 5
undefined-academy/semana-5 pull request #14
Opened 2023-04-25 05:01 UTC by JoseCamilo84

# Ejercicios de Semana 5
* Crear la clase Estudiante, variables privadas y métodos estáticos
* Mostrar los números del 1 al 10
* Mostrar los números del 1 al 10 pero usando "var"
* Crear un patrón con regex y filtrar una lista de correos

2023-04-25 06:55 UTC, facu1391 approved these changes
Buena esta perfecto.

2023-04-25 14:34 UTC, Alexis033 approved these changes
Hola, hasta donde puedo ver todo funciona muy bien.

2023-04-26 04:21 UTC, dfm555 requested changes
No puedes eliminar los archivos de tus compañeros, revisa la carpeta que eliminaste de Peke por favor.

2023-04-26 12:57 UTC, dfm555 approved these changes

2023-04-26 12:57 UTC, merged