PR Semana 5 - Aitorias#9443
undefined-academy/semana-5 pull request #15
Opened 2023-04-25 09:40 UTC by aitorias

### Clase 1 ejercicio: 

- [x] Crear una clase `Estudiante` con campos privados para el nombres y apellido, un _getter_ para el nombre completo y un método estático `fromObject`. 
- [x] Crear **función asíncrona** para calcular los promedios de calificaciones al cuadrado dado un array de estudiantes.
- [x] Imprimir el **nombre completo del estudiante y su promedio**.

### Clase 2 ejercicio:

- [x] Hacer una función que imprima los números del **1 al 10 cada segundo**

### Clase 3 ejercicio:

- [x] Hacer una función que imprima los números del **1 al 10 cada segundo** usando un bucle `for` con un `var`

### Clase 4 ejercicio:

- [x] Crear una funcionalidad que lea una lista de correos y **filtre los correos válidos** y **remueva la cadena de texto de _subaddressing_**

2023-04-25 18:06 UTC, DevOld112 requested changes
Hola amigo, que tal? Tengo gran parte de la mañana viendo tu codigo jajaja

Ejercicio 2, 3 y 4 :white_check_mark:

Pero cuando testee el ejercicio 01 en consola me devuelve esto:

`El/la estudiante undefined tiene un promedio de undefined`
`El/la estudiante undefined tiene un promedio de undefined`

No accede a las propiedades del array `estudiantesInfo` por alguna razon.

2023-04-25 18:29 UTC, aitorias commented
> Hola amigo, que tal? Tengo gran parte de la mañana viendo tu codigo jajaja
> 
> Ejercicio 2, 3 y 4 ✅
> 
> Pero cuando testee el ejercicio 01 en consola me devuelve esto:
> 
> `El/la estudiante undefined tiene un promedio de undefined` `El/la estudiante undefined tiene un promedio de undefined`
> 
> No accede a las propiedades del array `estudiantesInfo` por alguna razon.

¡Muchas gracias por la revisión! Creo que lo pude solucionar al corregir la línea de código 40:

```js
const promedios = estudiantes.map((estudiante) => {
```

2023-04-25 19:24 UTC, DevOld112 approved these changes
Excelente, ahora si funciona :)

2023-04-27 15:49 UTC, augaldecr approved these changes
Excelente trabajo. Cumple con todos los requerimientos y más

2023-04-27 18:30 UTC, aitorias commented
> Excelente, ahora si funciona :)

Genial, ¡muchas gracias por la revisión!

2023-04-27 18:30 UTC, aitorias commented
> Excelente trabajo. Cumple con todos los requerimientos y más

¡Muchas gracias por ayudar en la revisión!

2023-04-28 13:59 UTC, merged