Semana 5
undefined-academy/semana-5 pull request #17
Opened 2023-04-25 18:43 UTC by MauBedoya

* Se agregan ejercicios de semana 5

2023-04-26 21:25 UTC, facu1391 approved these changes
Hola como estas? Todo se puede ver perfecto y fácil lectura! Ahora podrías revisar mi PR?

2023-04-26 22:10 UTC, MauBedoya commented
> Hola como estas? Todo se puede ver perfecto y fácil lectura! Ahora podrías revisar mi PR?

hola! y gracias por la revision... ya pude ver tu PR, te deje unos comentarios, sería bueno que les des una mirada para ver si son correctos

2023-04-27 15:58 UTC, augaldecr requested changes
Buen trabajo. Único detalle es que en emailValidator.js está reemplazando el subaddresing por undefined. Diría que es cuestión de agregar el segundo parámetro a replace en la línea 18

2023-04-27 17:45 UTC, MauBedoya commented
> 

Cierto, no sé cómo se me paso revisar eso al copiarlo de mi borrador 😅, gracias por notarlo!

2023-04-29 01:52 UTC, LizethCs approved these changes
Cumple muy bien con los ejercicios de la semana 5👍

2023-04-29 04:05 UTC, fjquants approved these changes
Los ejercicios bien claros y cumplen con los requisitos solicitados

2023-04-29 13:08 UTC, MauBedoya commented
> Cumple muy bien con los ejercicios de la semana 5👍

Gracias por la revisión!

2023-04-29 13:09 UTC, MauBedoya commented
> Los ejercicios bien claros y cumplen con los requisitos solicitados

Gracias! 👍

2023-04-30 00:36 UTC, merged