feat: add exercises week 5
undefined-academy/semana-5 pull request #20
Opened 2023-04-26 00:48 UTC by sebasvalencia

Clase 1.

- Crea una clase Estudiante con campos privados para el nombre y apellido, un getter para el nombre completo y un método estático fromObject.
- Crea una función asíncrona calcularPromedios que acepte un array de estudiantes.
- Dentro de calcularPromedios, calcula el promedio de las calificaciones al cuadrado de cada estudiante.
- Imprime el nombre completo y el promedio de calificaciones de cada estudiante utilizando Template literals.

Clase 2.

- Hacer una función que imprima los números del 1 al 10, un número cada segundo.

Clase 3.

- Hacer una función que imprima los números del 1 al 10, un número cada segundo, pero usando un ciclo for con un var.

Clase 4.

- Crear una funcionalidad que lea una lista de correos y filtre los correos validos y remueva la cadena de texto de subaddresing.

2023-04-27 15:53 UTC, augaldecr requested changes
Buen trabajo. Único detalle es que en countTo10.js y en countTo10Var.js está imprimiendo del 0 al 9 y el requerimiento es de 1 a 10. Por lo demás, todo bien

2023-04-27 20:34 UTC, sebasvalencia commented
> Buen trabajo. Único detalle es que en countTo10.js y en countTo10Var.js está imprimiendo del 0 al 9 y el requerimiento es de 1 a 10. Por lo demás, todo bien

Super, gracias por el catch!

2023-04-27 21:23 UTC, augaldecr commented
> > Buen trabajo. Único detalle es que en countTo10.js y en countTo10Var.js está imprimiendo del 0 al 9 y el requerimiento es de 1 a 10. Por lo demás, todo bien
> 
> Super, gracias por el catch!

Perfecto. El problema fué corregido

2023-04-27 21:23 UTC, augaldecr approved these changes
Problema corregido. Excelente trabajo

2023-04-28 17:56 UTC, lucianogarriga approved these changes
Seba veo que se cumplen los requisitos exigidos para esta PR, el esquema de archivos está perfecto, las funciones desarrolladas están Ok, etc. Felicidades buen trabajo!

P.D.: Si puedes pasar a revisar mi PR te lo agradeceré! Te dejo el link => #25

2023-04-29 22:45 UTC, merged