Semana 5
undefined-academy/semana-5 pull request #22
Opened 2023-04-26 04:21 UTC by jaimecabrera911

Resolver los ejercicios en Javascript de la semana 5.

2023-04-26 22:57 UTC, DevOld112 requested changes
Hola bro, que tal?

Debes corregir el ejercicio 3, recuerda que se pide que declare dentro del ciclo for use `var` en vez de `let` ... recuerda que debes hacerla en un clousure para que pueda funcionar. Sigue asi :)

2023-04-26 23:18 UTC, jaimecabrera911 commented
> Hola bro, que tal?
> 
> Debes corregir el ejercicio 3, recuerda que se pide que declare dentro del ciclo for use `var` en vez de `let` ... recuerda que debes hacerla en un clousure para que pueda funcionar. Sigue asi :)

2023-04-26 23:19 UTC, jaimecabrera911 commented
> Hola bro, que tal?
> 
> Debes corregir el ejercicio 3, recuerda que se pide que declare dentro del ciclo for use `var` en vez de `let` ... recuerda que debes hacerla en un clousure para que pueda funcionar. Sigue asi :)

Ya se hizo la respectiva correccion, gracias

2023-04-26 23:27 UTC, DevOld112 commented
> > Hola bro, que tal?
> > Debes corregir el ejercicio 3, recuerda que se pide que declare dentro del ciclo for use `var` en vez de `let` ... recuerda que debes hacerla en un clousure para que pueda funcionar. Sigue asi :)
> 
> Ya se hizo la respectiva correccion, gracias

Vuelve a abrir el PR para darte el approve.

2023-04-27 01:07 UTC, DevOld112 approved these changes

2023-04-28 17:53 UTC, lucianogarriga approved these changes
Jaime veo que se cumplen los requisitos exigidos para esta PR, el esquema de archivos está perfecto, las funciones desarrolladas están Ok, etc. Felicidades buen trabajo!

2023-05-14 02:23 UTC, closed without merging