Ejercicios Semana 5
undefined-academy/semana-5 pull request #25
Opened 2023-04-27 15:49 UTC by lucianogarriga

# ⛺ Semana 5

Ejercicios de la quinta semana.

## 🏋Clase 1 [EJERCICIO]

1. Crea una clase Estudiante con campos privados para el nombre y apellido, un getter para el nombre completo y un método estático fromObject.
2. Crea una función asíncrona calcularPromedios que acepte un array de estudiantes.
3. Dentro de calcularPromedios, calcula el promedio de las calificaciones al cuadrado de cada estudiante.
4. Imprime el nombre completo y el promedio de calificaciones de cada estudiante utilizando Template literals.

### Usa el siguiente array de estudiantes como entrada:\*\*

```js
const estudiantesInfo = [
  { nombre: 'Ana', apellido: 'García', calificaciones: [3, 5, 4, 4.5] },
  { nombre: 'Luis', apellido: 'Pérez', calificaciones: [4.5, 4, 4, 5] }
];
```

## 🏋Clase 2 [EJERCICIO]

Hacer una función que imprima los números del 1 al 10, un número cada segundo.

## 🏋Clase 3 [EJERCICIO]

Hacer una función que imprima los números del 1 al 10, un número cada segundo, pero usando un ciclo `for` con un `var`.

## 🏋Clase 4 [EJERCICIO]

Crear una funcionalidad que lea una lista de correos y filtre los correos validos y remueva la cadena de texto de subaddresing.

```text
john.doe@example.com
jane_doe+shopping@example.org
alice.smith+work@example.co.uk
charlie.brown+newsletter@example.io
emily.watson+notes@example.net
```

1. Hacer fork del repositorio de la [semana-5](https://github.com/undefined-academy/semana-5)
2. Subir los ejercicios realizados anteriormente y crear el `pull request`.

### Estructura del PR

```text
.
└── exercises/
    └── lucianogarriga-1264/
        ├── Student.js
        ├── countTo10.js
        ├── countTo10Var.js
        └── emailValidator.js
```

2023-04-27 16:46 UTC, augaldecr requested changes
Hola. Compañero, no me funciona el código del emailValidator. 
`
Correo electronico valido
Correo electronico no valido
Correo electronico valido
Correo electronico valido
Correo electronico valido
Correo electronico valido
Correo electronico no valido
Línea 53
email
ReferenceError: email is not defined
`
Las demás parecen funcionar de forma correcta

Saludos

2023-04-27 21:30 UTC, lucianogarriga commented
> Hola. Compañero, no me funciona el código del emailValidator. `Correo electronico valido Correo electronico no valido Correo electronico valido Correo electronico valido Correo electronico valido Correo electronico valido Correo electronico no valido Línea 53 email ReferenceError: email is not defined` Las demás parecen funcionar de forma correcta
> 
> Saludos

@augaldecr hola gracias por tu recomendación! Acabo de hacer unos cambios y ahora se puede ver por consola qué correos son los válidos. Quedo atento a tu revisión!

2023-04-27 22:40 UTC, augaldecr approved these changes
Corregido. Listo

2023-04-28 18:03 UTC, sebasvalencia commented
Hola Luciano, quedo nítido el trabajo, felicitaciones!!!

2023-04-28 18:03 UTC, sebasvalencia approved these changes

2023-04-28 18:07 UTC, lucianogarriga commented
> Hola Luciano, quedo nítido el trabajo, felicitaciones!!!

Muchas gracias por tu devolución y por tu tiempo Seba!!

2023-05-01 16:52 UTC, merged