Ejercicios de la semana 5 añadidos
undefined-academy/semana-5 pull request #26
Opened 2023-04-28 17:07 UTC by marcospenalosa

Añadidos los ejercicios de la semana 5.

2023-04-29 02:53 UTC, LizethCs requested changes

2023-04-29 02:53 UTC, LizethCs commented on exercises/murquis-5340/emailValidator.js
> +console.log(emailList
Hola👋 
Al mostrar en consola la lista de correos válidos debería mostrar el correo `alice.smith+work@example.co.uk` como válido pero no lo hace y en Student.js los promedios deberían ser aprox. : 17 el de Ana y 19 el de Luis, te recomendaría mirar eso. De resto lo veo muy bien

2023-04-29 04:21 UTC, fjquants commented
En el ejercicio de Student, se requiere calcular el promedio al cuadrado. 
En el ejercicio de validar correos a como indica LizethCs debería poder validar ese tipo de dominio. Puedes revisar en la pagina regex101.com para validarlo.

Saludos

2023-04-29 04:22 UTC, fjquants requested changes
Validar la expresión regular

2023-05-02 14:39 UTC, marcospenalosa commented
Buenas; 
He corregido los errores indicados.

2023-05-02 15:40 UTC, LizethCs approved these changes

2023-05-02 16:20 UTC, fjquants approved these changes

2023-05-02 19:08 UTC, merged