PR - Semana 5
undefined-academy/semana-5 pull request #27
Opened 2023-04-28 18:18 UTC by LizethCs

PR de la semana 5

2023-04-28 22:53 UTC, MauBedoya requested changes
El ejercicio de "emailValidator" parece no estar entregando las respuestas correctas, habría que darle una mirada a la expresión regular. Los demás ejercicios están muy buenos 👌
También te agradecería si le puedes dar una mirada a mi PR y quizá dejar algún comentario 👀

2023-04-28 22:53 UTC, MauBedoya commented on exercises/Lizeth-9127/emailValidator.js
> +  const regExp = /^[\w0-9]+(\.[0-9\+\w-]+)*@([\w-]+\.)+[a-zzA-Z]{2,}$/;
parece que estas condicionando a que siempre exista un punto antes del sub address, por eso el segundo correo te regresa como invalido cuando debería ser valido. Esto pasa por que pusiste el "\." por delante en la siguiente sección:
```js
...(\.[0-9\+\w-]+)*...
```
Tambien estas usando "\w", en varias partes, con "0-9" y si bien no está mal, quizá no es necesario ya que "\w" ya reconoce números.

2023-04-29 01:34 UTC, LizethCs commented on exercises/Lizeth-9127/emailValidator.js
> +  const regExp = /^[\w0-9]+(\.[0-9\+\w-]+)*@([\w-]+\.)+[a-zzA-Z]{2,}$/;
Respecto a lo del segundo correo, tenía entendido que no se permiten guiones bajos en una dirección de correo  (peroo al parecer esto es solo cosa de gmail), por lo que pensé que el segundo correo era inválido jsjsjs
Ya miro tu PR👍

2023-04-29 04:17 UTC, fjquants requested changes

2023-04-29 04:17 UTC, fjquants commented on exercises/Lizeth-9127/emailValidator.js
> +  const regExp = /^[\w]+([\.\+\w]+)?@([\w-]+\.)+[a-zzA-Z]{2,}$/;
Revisar el regExp para que pueda entregar el resultado requerido. Puedes revisar el regExp en su página regex101.com para validar el resultado de la misma.

2023-04-29 12:24 UTC, MauBedoya commented on exercises/Lizeth-9127/emailValidator.js
> +  const regExp = /^[\w0-9]+(\.[0-9\+\w-]+)*@([\w-]+\.)+[a-zzA-Z]{2,}$/;
jajaj suele pasar, es medio confuso a un principio el tema de acomodar y agrupar las cosas para que no se cuelen detalles así en las RegExp

2023-04-29 12:24 UTC, MauBedoya approved these changes

2023-04-29 12:48 UTC, fjquants approved these changes

2023-04-29 23:25 UTC, merged