ejercicios de la semana 5
undefined-academy/semana-5 pull request #28
Opened 2023-04-28 21:07 UTC by fjquants

Realizado los ejercicios de la semana 5

**Ejercicio 1** _Manejo de  arrays_
Se crea funcion para calcula el promedio de las calificaciones de los estudiantes en el array dado.

**Ejercicio 2** _Función para mostrar los números del 1 al 10_
Mediante uso de for y setTimeout se crea función para mostrar los números del 1 al 10 cada segundo

**Ejercicio 3** _Función para mostrar los números del 1 al 10 usando var_
Se sustituye "let"  por "var" para declarar variables  y se crea función para mostrar los números del 1 al 10 cada segundo

**Ejercicio 4** _Filtrado de correos_
Con el uso de regex se realiza filtrado de correos para mostrar los correos correctos eliminando los subaddresing.

Al inicio me costó, pero poco a poco fui entendiendo la sintaxis.

2023-04-28 23:09 UTC, MauBedoya requested changes
Parece que dos de los ejercicios no están funcionando del todo bien, te deje unos comentarios para que les des una mirada. También te agradecería que si puedes le des una mirada a mi PR 👀

2023-04-28 23:09 UTC, MauBedoya commented on exercises/fjquant-2458/Student.js
recuerda que el ejercicio te pide "calcula el promedio de las calificaciones **al cuadrado** de cada estudiante"

2023-04-28 23:09 UTC, MauBedoya commented on exercises/fjquant-2458/emailValidator.js
> +const emailregex = /^[\w.]+(\+[\w]+)?@[\w]+\.[\w]{2,7}$/
Parece que falta especificar que se tomen en cuenta los guiones "-" como carácter valido, y también se debería tomar como validos los correos con dominios de tercer nivel o superior (como es el caso de **alice.smith+work@example`.co.uk`**)

2023-04-29 04:02 UTC, fjquants commented on exercises/fjquant-2458/Student.js
Muchas gracias @MauBedoya, ya realicé el cambio en la función

2023-04-29 04:02 UTC, fjquants commented on exercises/fjquant-2458/emailValidator.js
> +const emailregex = /^[\w.]+(\+[\w]+)?@[\w]+\.[\w]{2,7}$/
Hola @MauBedoya en el regex el punto luego de la w, valida "todo lo demás" luego de la palabra.
Reescribí el regex para que valide los dominios de tercer nivel.

2023-04-29 12:48 UTC, MauBedoya commented on exercises/fjquant-2458/emailValidator.js
> +const emailregex = /^[\w.]+(\+[\w]+)?@[\w]+\.[\w]{2,7}$/
Dentro de un "juego de caracteres" (los corchetes) el punto deja de actuar como selector "universal" por decirlo de alguna manera, y toma significado del carácter "punto" normal. Aquí un ejemplo de tu regexp funcionando:
![image](https://user-images.githubusercontent.com/111880575/235303093-2d590f2d-cdd1-4456-a48d-dcabda0aab13.png)
En caso de que quieras seguir usando el "selector universal" tendrías que utilizar un **grupo de captura**, pero no estoy seguro de si eso traería algún otro problema en las validaciones con caracteres que no deberían estar, para evitar cualquier problema podrías usar el "-" como carácter final dentro de los corchetes.
Puedes revisar lo del "selector universal" y el "juego de caracteres" en estos links:
[Clases de caracteres](https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Regular_expressions/Character_classes)
[Grupos y rangos](https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Regular_expressions/Groups_and_backreferences)

2023-04-30 03:39 UTC, fjquants commented on exercises/fjquant-2458/emailValidator.js
> +const emailregex = /^[\w.]+(\+[\w]+)?@[\w]+\.[\w]{2,7}$/
Realice nuevo ajuste en regex para que me reconozca el "-". Gracias por el consejo. Puedes validar si así estaría?

2023-04-30 03:58 UTC, MauBedoya approved these changes

2023-04-30 18:16 UTC, DevOld112 approved these changes
Todo funciona excelente. Tienes mi approve.

2023-04-30 21:50 UTC, merged