Ejercicios semana 5
undefined-academy/semana-5 pull request #31
Opened 2023-04-29 23:20 UTC by luanarmo

-🎈Hacer un fork al repositorio de la semana 5
- 🔗 Clonar el repositorio forkeado.
- 📂 Dentro de la carpeta sxercises subir el código de los 4 ejercicios
- 📩 Ir al repositorio de la semana forkeado y crear el pull request.

2023-04-30 12:50 UTC, DevOld112 requested changes
Compañero tu codigo es entedible, y el ejercicio 01, 02 y 03 estan bien.

El inconveniente esta en el ejercicio de `emailValidator.js` en la primera linea define el array emails con un `const` porque si no va a dar error.

2023-04-30 14:35 UTC, luanarmo commented
@DevOld112 gracias por la observación, lo acabo de corregir 😁

2023-04-30 15:01 UTC, DevOld112 approved these changes
Excelente ahora si.

2023-05-02 19:54 UTC, Pancratzia approved these changes
Hola! Todos tus ejercicios están perfectos y listos para merge. Sigue así

2023-05-02 19:55 UTC, lucianogarriga approved these changes
Veo que los ejercicios se encuentran completos y cumplen con lo requerido. Buen trabajo, felicidades!

2023-05-08 03:52 UTC, merged