Ejercicios completos de Semana 5
undefined-academy/semana-5 pull request #32
Opened 2023-04-30 06:40 UTC by therojo

Envio para aprobación, los 4 ejercicios de semana - 5

2023-04-30 13:26 UTC, DevOld112 requested changes
Compañeros del bootcamp consulta: no habria problemas con el merge si en este caso no nombra los archivos como especifico el profe Guille en el repositorio original de la semana 5?

```text
.
└── exercises/
    └── glrodasz-0666/
        ├── Student.js
        ├── countTo10.js
        ├── countTo10Var.js
        └── emailValidator.js
```

2023-04-30 13:26 UTC, DevOld112 commented on exercises/Rojo-7011/4_functional_and_regex_emails.js
Compañero una pequeña modificacion en el codigo en la linea 9, define a `emails` con `const` para que al testear el codigo no genere un error

2023-04-30 13:26 UTC, DevOld112 commented on exercises/Rojo-7011/3_asincronismo_count_10_delay_one_second_using_var.js
Compañero, hay varios errores en el codigo, aqui tienes que hacer el uso de un clousure (encerrar una funcion dentro de otra funcion) luego del ciclo for para encerrar el valor de var. Al no hacerlo puede retornarte 10 veces `11` como resultado o en tu caso `undefined` 10 veces.

Para solventar esto rescribi tu codigo de la siguiente manera:

```
const ONE_SECOND_IN_MILISECONDS = 1000

function printNumber(number) {  
    for(var i=1; i<=10; i++){
        (function(i){
            setTimeout(function(){
                console.log(i);
            }, (i + 1)*ONE_SECOND_IN_MILISECONDS)
        })(i);
        
    }
}

printNumber(10);
```

Me comentas luego que tal. Estare atento.

2023-04-30 23:53 UTC, DevOld112 requested changes
El codigo funciona perfectamente felicidades, se entiende! pero cuentame algo. Veo que dice que tienes conflictos para hacer Merge, que te detalla github?

2023-05-01 01:48 UTC, therojo commented
Gracias por las revisiones DevOld112, tienes razón, marca un conflicto en el archivo  oculto .gitkeep que esta en raiz de exercises, uso Linux,  tal vez como lo describe el mensaje, sea un problema de permisos, pero no se si sea en mi local.

Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

2023-05-01 01:51 UTC, therojo commented
Sobre la nomenclatura de los ejercicios, quiza si haya algun problema, porque me parece que Guillermo Rodas dijo que haria algo automatico para acelerar esto de las revisiones, pero no se en si que sea.

Creo que puedo renombrarlos y volver a hacer commit para que cumplan con la nomenclatura especificada.

Gracias por decirlo, la verdad no lei esa indicacion.

2023-05-01 13:59 UTC, DevOld112 commented
> Sobre la nomenclatura de los ejercicios, quiza si haya algun problema, porque me parece que Guillermo Rodas dijo que haria algo automatico para acelerar esto de las revisiones, pero no se en si que sea.
> 
> Creo que puedo renombrarlos y volver a hacer commit para que cumplan con la nomenclatura especificada.
> 
> Gracias por decirlo, la verdad no lei esa indicacion.

Intenta renombrarlo para ver si solventa el conflicto

2023-05-17 02:22 UTC, closed without merging