Week 5. Commiting the excercises for Week 5
undefined-academy/semana-5 pull request #36
Opened 2023-05-01 08:45 UTC by juanfrasca

**Clase 1**
Crea una clase Estudiante con campos privados para el nombre y apellido, un getter para el nombre completo y un método estático fromObject.
Crea una función asíncrona calcularPromedios que acepte un array de estudiantes.
Dentro de calcularPromedios, calcula el promedio de las calificaciones al cuadrado de cada estudiante.
Imprime el nombre completo y el promedio de calificaciones de cada estudiante utilizando Template literals.

Archivo: students.js

---
**Clase 2**
Hacer una función que imprima los números del 1 al 10, un número cada segundo.

Archivo: async.js

---
**Clase 3**
Hacer una función que imprima los números del 1 al 10, un número cada segundo, pero usando un ciclo for con un `var`.

Archivo: asyncvar.js

---
**Clase 4**
Crear una funcionalidad que lea una lista de correos y filtre los correos validos y remueva la cadena de texto de *subaddresing*.

`john.doe@example.com`
`jane_doe+shopping@example.org`
`alice.smith+work@example.co.uk`
`charlie.brown+newsletter@example.io`
`emily.watson+notes@example.net`

Archivo: regex.js

2023-05-01 14:23 UTC, DevOld112 approved these changes
Todo excelente :)

2023-05-02 19:16 UTC, marcospenalosa requested changes
Además de modificar el reduce, deberías usar el mismo esquema de archivos que indica el ejercicio, es decir, se deberían de cambiar los nombres de los archivos.
El resto está correcto.

2023-05-02 19:16 UTC, marcospenalosa commented on exercises/juanfrasca-7848/students.js
Hay un fallo en el reduce, no calcula correctamente el promedio, busca en la documentación o en mi PR, porque yo tuve el mismo fallo 😅

2023-05-09 08:56 UTC, juanfrasca commented on exercises/juanfrasca-7848/students.js
Muchas gracias por el feedback! Ahora voy a trabajar en eso

2023-05-25 02:21 UTC, closed without merging