ejercicios semana5
undefined-academy/semana-5 pull request #39
Opened 2023-05-02 00:40 UTC by DanaiKongpan

2023-05-02 13:30 UTC, DevOld112 requested changes
Amigo los archivos estan vacios

2023-05-02 19:51 UTC, lucianogarriga requested changes
Revisar los archivos, ya que todos estan vacíos. Una vez que realices los ejercicios me avisas así lo corroboro y en caso de estar OK los apruebo.

2023-05-04 19:45 UTC, DanaiKongpan commented
> Amigo los archivos estan vacios

Gracias

2023-05-04 19:45 UTC, DanaiKongpan commented
Corrección

2023-05-04 19:46 UTC, DanaiKongpan commented
> Revisar los archivos, ya que todos estan vacíos. Una vez que realices los ejercicios me avisas así lo corroboro y en caso de estar OK los apruebo.

Gracias ya hice las correcciones

2023-05-04 23:35 UTC, lucianogarriga approved these changes
Los ejercicios están Ok. Respecto del de emailValidator, si saca los subadressing, pero si coloco por ejemplo  `john.doe@example.comcom.ar.org` lo considera como válido (cuestión que no debería de serlo). De todos modos considero que está apto para su aprobación. Felicidades!

2023-05-21 02:27 UTC, closed without merging