Semana-5
undefined-academy/semana-5 pull request #41
Opened 2023-05-02 21:47 UTC by EdwinOrtizCantillo

## Ejercicio 1
1. Crea una clase Estudiante con campos privados para el nombre y apellido, un getter para el nombre completo y un método estático fromObject.
2. Crea una función asíncrona calcularPromedios que acepte un array de estudiantes.
3. Dentro de calcularPromedios, calcula el promedio de las calificaciones al cuadrado de cada estudiante.
4. Imprime el nombre completo y el promedio de calificaciones de cada estudiante utilizando Template literals.

## Ejercicio 2

- Hacer una función que imprima los números del 1 al 10, un número cada segundo.

## Ejercicio 3

- Hacer una función que imprima los números del 1 al 10, un número cada segundo, pero usando un ciclo for con un var.

## Ejercicio 4

Crear una funcionalidad que lea una lista de correos y filtre los correos validos y remueva la cadena de texto de subaddresing.

```sh
john.doe@example.com
jane_doe+shopping@example.org
alice.smith+work@example.co.uk
charlie.brown+newsletter@example.io
emily.watson+notes@example.net
```

2023-05-03 01:43 UTC, Pancratzia requested changes
Hola! Tienes un pequeño error en Student.js... Los demás ejercicios están perfectos

2023-05-03 01:43 UTC, Pancratzia commented on exercises/Edwin_Ortiz-3619/Student.js
> +            const student = Student.fromObjet({
Tienes un typo en esta línea, y por ello el código da error. Deberías llamar a `Student.fromObject`

2023-05-03 02:05 UTC, EdwinOrtizCantillo commented on exercises/Edwin_Ortiz-3619/Student.js
> +            const student = Student.fromObjet({
Dale gracias ya lo corrijo

2023-05-04 18:53 UTC, EdwinOrtizCantillo commented on exercises/Edwin_Ortiz-3619/Student.js
> +            const student = Student.fromObjet({
@Pancratzia Ya hice la corrección lo vuelves a mirar porfa

2023-05-05 15:40 UTC, Pancratzia approved these changes

2023-05-22 11:01 UTC, Jorem999 approved these changes
Hola Edwin  👋 
Todo bien!

2023-05-24 19:29 UTC, lucianogarriga approved these changes
Excelente los ejercicios Edwin, y la descripción del README.md de la PR me pareció fantástico! Felicidades!

2023-05-28 18:30 UTC, EdwinOrtizCantillo commented
> Excelente los ejercicios Edwin, y la descripción del README.md de la PR me pareció fantástico! Felicidades!

Gracias hermano

2023-05-30 01:14 UTC, merged