Finishing week 5 with the right foot
undefined-academy/semana-5 pull request #45
Opened 2023-05-03 01:03 UTC by Josofico

# In this code, we're gonna show how we can complete this exercises in the way we know.

2023-05-03 19:38 UTC, lucianogarriga requested changes
En líneas generales los ejercicios se ven bien. Recomiendo:
1. Eliminar el archivo .gitkeep
2. Modificar el archivo README.md de la PR, y realizar una descripción sobre las consignas a resolver en cada ejercicio

2023-05-03 19:38 UTC, lucianogarriga commented on exercises/.gitkeep
Recomiendo eliminar este archivo que no es necesario subir a la PR

2023-05-03 22:21 UTC, Josofico commented on exercises/.gitkeep
Es raro porque yo lo elimine en mi repositorio.

2023-05-03 22:22 UTC, Josofico commented on exercises/.gitkeep
![Screenshot_43](https://user-images.githubusercontent.com/104795604/236062759-f798899a-fe4a-40bb-8fd1-71d5b10d1ea1.png)

2023-05-03 22:23 UTC, Josofico commented on exercises/.gitkeep
Me sale que pertenece en el archivo de Guille.

2023-05-03 22:25 UTC, Josofico commented on exercises/.gitkeep
De que forma dices que debo editar el README, dices el original del PR?

2023-05-12 03:08 UTC, Lealdos approved these changes
all done for me

2023-05-12 14:11 UTC, lucianogarriga approved these changes
Los ejercicios están OK, sólo recomendaría modificar el archivo README.md de la PR, y realizar una descripción sobre las consignas a resolver en los ejercicios.

2023-05-12 14:11 UTC, lucianogarriga commented on exercises/.gitkeep
> Me sale que pertenece en el archivo de Guille.

Me parece raro, en mi PR no me figura tal archivo. Fijate de removerlo del repositorio remoto, no del local como figura en la captura que pasaste

2023-05-12 14:11 UTC, lucianogarriga commented on exercises/.gitkeep
> De que forma dices que debo editar el README, dices el original del PR?

Sisi ese mismo. Si quieres revisar como hice el mío #25, para que cualquier persona de afuera que mire tu PR entienda en qué consistió cada ejercicio (es para darle mayor prolijidad, no es que sea obligatorio, mas alla que Guillermo pidió desde la PR 1 que lo expliquemos).

2023-05-12 18:20 UTC, cadifilippo requested changes
Los archivos deberían estar en una subcarpeta con tu nombre de usuario

2023-05-14 15:10 UTC, Josofico reviewed
Files in the right place.

2023-05-14 15:10 UTC, Josofico reviewed
FIles in the right place.

2023-05-15 02:38 UTC, merged