Ejercicios de la semana 5
undefined-academy/semana-5 pull request #69
Opened 2023-05-30 05:32 UTC by StephanyCS1

# Ejercicios semana 5

1. Ejercicio de crear una clase de estudiantes
2. Ejercicio contar con let
3. Ejercicio con var
4. Ejercicio de validador de correos con regex 🤯

2023-06-01 21:49 UTC, EzequielCaste requested changes

2023-06-01 21:49 UTC, EzequielCaste commented on exercises/Tefis96-9675/countTo10.js
> +const oneSeg = 1000;
@StephanyCS1 justamente hace lo contrario, cuenta del 10 a 1
por favor corregir ;)

2023-06-01 21:49 UTC, EzequielCaste commented on exercises/Tefis96-9675/countTo10Var.js
> +
lo mismo que el ejercicio anterior, 
la consigna dice "del 1 al 10" no del 10 a 1

2023-06-02 13:19 UTC, lucianogarriga requested changes
Stephany, los ejercicios en líneas generales están ok. Pero los contadores están realizados de manera inversa, en lugar de que i comience en 1 hasta el 10, lo has realizado al revez, por lo que comienza en 10 y resta hasta llegar a 1.
Me avisas cuando corrijas eso y apruebo tu PR!

2023-06-03 23:16 UTC, StephanyCS1 commented on exercises/Tefis96-9675/countTo10Var.js
> +
Hola, muchas gracias por tu feedback

Ya solucioné el error 😁

2023-06-03 23:16 UTC, StephanyCS1 commented
> Stephany, los ejercicios en líneas generales están ok. Pero los contadores están realizados de manera inversa, en lugar de que i comience en 1 hasta el 10, lo has realizado al revez, por lo que comienza en 10 y resta hasta llegar a 1. Me avisas cuando corrijas eso y apruebo tu PR!

😁 Muchas gracias, ya lo solucioné

2023-06-19 02:32 UTC, closed without merging