Ejercicios Semana-5 bR#3929
undefined-academy/semana-5 pull request #7
Opened 2023-04-22 19:16 UTC by bEERRE96

1. Se creo una class Student, con un respectivo get y un metodo static fromObject.
2. Se creo una funcion que cuenta del 1 al 10, imprimiendo un numero por cada segundo.
3. Se modifico la funcion de conteo, intercambiando la variable declarada con let por var.
4. Se creo una funcion que filtra una lista de mails, y les remueve el subadressing.

2023-04-23 00:32 UTC, DevOld112 requested changes
Hola que tal? Por alguna razón que aun no logro entender, el ejercicio 3 (con var) me devuelve undefined

2023-04-23 01:27 UTC, DevOld112 commented
> Hola que tal? Por alguna razón que aun no logro entender, el ejercicio 3 (con var) me devuelve undefined

Listo, ya entendi. Para que pueda funcionar necesitas hacer un Clousure para encerrar el valor de i dentro del ciclo for. Si tienes dudas, me comentas.

2023-04-23 02:17 UTC, bEERRE96 commented
> > Hola que tal? Por alguna razón que aun no logro entender, el ejercicio 3 (con var) me devuelve undefined
> 
> Listo, ya entendi. Para que pueda funcionar necesitas hacer un Clousure para encerrar el valor de i dentro del ciclo for. Si tienes dudas, me comentas.

Hola, si recien tire el codigo y me generaba error tambien, era una cuestion de sintaxis al parecer, ya la corregi y me esta corriendo bien el conteo, cualquier cosa avisame si sigue sin funcionar

2023-04-23 14:23 UTC, DevOld112 commented
> > > Hola que tal? Por alguna razón que aun no logro entender, el ejercicio 3 (con var) me devuelve undefined
> > 
> > 
> > Listo, ya entendi. Para que pueda funcionar necesitas hacer un Clousure para encerrar el valor de i dentro del ciclo for. Si tienes dudas, me comentas.
> 
> Hola, si recien tire el codigo y me generaba error tambien, era una cuestion de sintaxis al parecer, ya la corregi y me esta corriendo bien el conteo, cualquier cosa avisame si sigue sin funcionar

Compañero, ahora si funciona, solamente como recomendacion agregaria llamar a la funcion `main()` al final del codigo para que se ejecute. De resto ahora si tienes mi approve

2023-04-23 14:23 UTC, DevOld112 approved these changes

2023-04-27 15:46 UTC, augaldecr approved these changes
Buen trabajo. Cumple con todos los requerimientos

2023-04-28 13:59 UTC, merged