Semana-5 Undefined Academy
undefined-academy/semana-5 pull request #70
Opened 2023-06-01 16:16 UTC by QuirogaPau

2023-06-01 18:27 UTC, aitorias requested changes
¡Hola Paula! Revisé las actividades correspondientes a la PR de la semana 5 y te hice algunos comentarios para que pudieras revisarlos. Únicamente, tienes dos actividades que parecen no ser correctas, el resto están perfectas! 😋

2023-06-01 18:27 UTC, aitorias commented on exercises/PaulaQuiroga-8406/countTo10Var.js
Este ejercicio no devuelve los valores del 1 al 10 (te puse una captura de muestra). Como pista o consejo, te recomiendo que eches un vistazo a las **funciones _closure_**

![image](https://github.com/undefined-academy/semana-5/assets/6051056/7e8a9bb8-1010-4de9-8112-c93b66049fdf)

2023-06-01 18:27 UTC, aitorias commented on exercises/PaulaQuiroga-8406/student.js
> +        const scoresSum = scores.reduce((acum, score) =>
El código está genial, pero los valores que te dan de promedio no son correctos o tan precisos. Parece que el problema está en este cálculo, que no le has proporcionado un valor inicial al **acumulador** de la función `reduce`.

2023-06-02 13:16 UTC, lucianogarriga requested changes
Hola Pau, he revisado tus ejercicios y en líneas generales están bastante bien.
Como recomendación de correcciones:
1. Como te dijo nuestro compañero, la función reduce en el ejercicio "student" no arroja un promedio preciso,
2. En el contador con var, por consola imprime directamente el número 11,
3. En el README de la PR lo has dejado vacío. Te recomiendo que realices una breve descripción respecto de qué se trata cada ejercicio, así cualquier persona que lea tu código sepa la consigna.
Cuando lo corrijas me avisas así te apruebo tu PR!

2023-06-18 02:43 UTC, closed without merging