PR semana-5
undefined-academy/semana-5 pull request #72
Opened 2023-06-05 22:18 UTC by dhdarken

🏋Clase 1 [EJERCICIO]
Crea una clase Estudiante con campos privados para el nombre y apellido, un getter para el nombre completo y un método estático fromObject.
Crea una función asíncrona calcularPromedios que acepte un array de estudiantes.
Dentro de calcularPromedios, calcula el promedio de las calificaciones al cuadrado de cada estudiante.
Imprime el nombre completo y el promedio de calificaciones de cada estudiante utilizando Template literals.
Usa el siguiente array de estudiantes como entrada:**
const estudiantesInfo = [
  { nombre: 'Ana', apellido: 'García', calificaciones: [3, 5, 4, 4.5] },
  { nombre: 'Luis', apellido: 'Pérez', calificaciones: [4.5, 4, 4, 5] }
];
🏋Clase 2 [EJERCICIO]
Hacer una función que imprima los números del 1 al 10, un número cada segundo.

🏋Clase 3 [EJERCICIO]
Hacer una función que imprima los números del 1 al 10, un número cada segundo, pero usando un ciclo for con un var.

🏋Clase 4 [EJERCICIO]
Crear una funcionalidad que lea una lista de correos y filtre los correos validos y remueva la cadena de texto de subaddresing.

john.doe@example.com
jane_doe+shopping@example.org
alice.smith+work@example.co.uk
charlie.brown+newsletter@example.io
emily.watson+notes@example.net
Hacer fork del repositorio de la [semana-5](https://github.com/undefined-academy/semana-5)
Subir los ejercicios realizados anteriormente y crear el pull request.
Estructura del PR
.
└── exercises/
    └── glrodasz-0666/
        ├── Student.js
        ├── countTo10.js
        ├── countTo10Var.js
        └── emailValidator.js

2023-06-07 04:07 UTC, MrRedu requested changes
**El ejercicio de RegExp está de maravilla**, en los otros te dejé unos micro-cambios, cuando los hagas tienes approved seguro.

Tengo dos cosas más como recomendación aisladas a los ejercicios;
1. _**No pongas espacios en los nombres de los archivos**_, jaja.
2. Intenta _**correr el código por tu cuenta antes de mandarlo a P**R_, porque literalmente el de la clase no funcionaba desde un principio

En general, todo super bien

2023-06-07 04:07 UTC, MrRedu commented on exercises/dhdarken-5806/student.js
> +calculateAverage(studentsInfo);
1. El nombre de la clase, por convención debería comenzar con mayúscula.
2. El método getter de tu clase, está usando la notación PascalCase (comienza con mayúscula) ⚠es recomendable la camelCase.
3. Las calificaciones (scores), están guardados como un string, lo cual te "inhabilita" todo el código que sigue. Claro que solo toca cambiarlo a un array para que funcione
4. En la línea 22, el método estático "fromObject" hace referencia a la clase, por lo que debería ser `Student.fromObject`, con la `s` mayúscula para que haga referencia a la clase. Claro que esto está así porque nombramos la clase con minúscula, pero cuando lo cambies, lo tengas en cuenta.
5. Bueno, el método reduce no funcionaba porque teniamos los scores como string, pero después del paso 3 ya debería andar
6. Después de hacer todos esos cambios, ya se pueden sacar los promedios, pero el fullname sale como "Undefined" y la verdad no encontré el por qué 🤣🤣🤣 _si lo encuentras, me dices, porque me mata la curiosidad_

2023-06-07 04:07 UTC, MrRedu commented on exercises/dhdarken-5806/count 1 to 10 var
> +}
Personalmente esto me imprime algo como:
![image](https://github.com/undefined-academy/semana-5/assets/73679190/0a8cc2f6-889f-4c66-a40f-9abbe9262d3d)
Luego intenté con cada función por separado, y aún así hay algo que no está del todo correcto. Imprime un número de más

2023-06-07 04:07 UTC, MrRedu commented on exercises/dhdarken-5806/count 1 to 10
> +}
No entiendo el objetivo de la primera función, aunque supondré que fue algo que se te vino a la mente, lo hiciste y luego olvidaste borrarlo o algo así, jaja. Pero está bueno.

Con respecto a la segunda función, que es la que respecta al ejercicio, está bien. Yo le quitaría los corchete a la `i` que está dentro del console.log, pero meeeh, la verdad no importa.

2023-06-07 17:38 UTC, dhdarken commented on exercises/dhdarken-5806/count 1 to 10 var
> +}
la funcion de arriba creo que imprime uno de mas por que tiene el <= y no puedes correr las 2 al mismo tiempo por que el var es global se sale del scope o eso es lo que pienso :s

2023-06-07 17:39 UTC, dhdarken commented on exercises/dhdarken-5806/count 1 to 10
> +}
la verdad primero hice la de arriba y ya luego intente lo mismo pero esta vez con letras como para practicar un poco mas

2023-06-07 17:50 UTC, dhdarken commented on exercises/dhdarken-5806/student.js
> +calculateAverage(studentsInfo);
ya lo corregi todo lo que me dijiste pero me arroja el undefined voy a buscar

2023-06-07 19:04 UTC, dhdarken commented on exercises/dhdarken-5806/student.js
> +calculateAverage(studentsInfo);
ya encontre el problema con el undefined era que la funcion constructora lo habia copiado mal basicamente un error de letra muchas gracias

2023-06-08 06:42 UTC, MrRedu approved these changes

2023-06-15 02:01 UTC, FreivysDev commented on exercises/dhdarken-5806/student.js
Muy bien todo

2023-06-15 02:03 UTC, FreivysDev commented on exercises/dhdarken-5806/count1to10.js
Excelente 👍

2023-06-15 02:03 UTC, FreivysDev approved these changes
Muy bien lo ejercicios 👍

2023-06-15 17:47 UTC, merged