these are the exercises for week 5
undefined-academy/semana-5 pull request #78
Opened 2023-06-22 16:54 UTC by rrodriguezca

Exercises for week 5

2023-06-23 00:10 UTC, jorge9372 requested changes

2023-06-23 00:10 UTC, jorge9372 commented on exercises/rrodriguezca-2238/student.js
> +        return new Student(nombre, apellido);
Aca debes usar los mismos nombres de name y lastName

2023-06-23 00:10 UTC, jorge9372 commented on exercises/rrodriguezca-2238/student.js
> +    const averages = students.map(({ name, lastname, grades }) => {
lastName*

2023-06-23 00:10 UTC, jorge9372 commented on exercises/rrodriguezca-2238/student.js
> +        const averagesSum = grtades.reduce((acum, grade) => acum + grade, 0)
Esta mal escrito grades

2023-06-23 00:10 UTC, jorge9372 commented on exercises/rrodriguezca-2238/student.js
> +    average.forEach(({ fullName, average }) => {
averages*

2023-06-23 00:10 UTC, jorge9372 commented on exercises/rrodriguezca-2238/student.js
> +        console.log(`${fullName}: ${average ** 2}`)
Acá estas elevando todo el promedio al cuadrado, si no me equivoco lo que se pide es que primero eleves al cuadrado cada promedio, los sumes y lo dividas entre el número de promedios.

2023-06-23 00:37 UTC, rrodriguezca commented on exercises/rrodriguezca-2238/student.js
> +        return new Student(nombre, apellido);
> Aca debes usar los mismos nombres de name y lastName

Listo.

2023-06-23 00:37 UTC, rrodriguezca commented on exercises/rrodriguezca-2238/student.js
> +    const averages = students.map(({ name, lastname, grades }) => {
> lastName*

listo.

2023-06-23 00:37 UTC, rrodriguezca commented on exercises/rrodriguezca-2238/student.js
> +        const averagesSum = grtades.reduce((acum, grade) => acum + grade, 0)
> Esta mal escrito grades

corregido

2023-06-23 00:38 UTC, rrodriguezca commented on exercises/rrodriguezca-2238/student.js
> +    average.forEach(({ fullName, average }) => {
> averages*

corregido

2023-06-23 00:40 UTC, rrodriguezca commented on exercises/rrodriguezca-2238/student.js
> +        console.log(`${fullName}: ${average ** 2}`)
> Acá estas elevando todo el promedio al cuadrado, si no me equivoco lo que se pide es que primero eleves al cuadrado cada promedio, los sumes y lo dividas entre el número de promedios.

Acá dice "Dentro de calcularPromedios, calcula el promedio de las calificaciones al cuadrado de cada estudiante.". Es el promedio al cuadrado. Al compilar  en el console me sale el resultado:

 calculateAverages(studentsInfo)

VM56:39 García García: 17.0569
VM56:39 Pérez Pérez: 19.1844

2023-06-23 00:54 UTC, jorge9372 commented on exercises/rrodriguezca-2238/student.js
> +        console.log(`${fullName}: ${average ** 2}`)
Si, está bien, es que si te fijas se puede interpretar como el promedio total al cuadrado, o que eleves al cuadrado las calificaciones de cada estudiante y a eso le saques el promedio..

2023-06-23 00:59 UTC, jorge9372 requested changes

2023-06-23 00:59 UTC, jorge9372 commented on exercises/rrodriguezca-2238/student.js
>          console.log(`${fullName}: ${average ** 2}`)
Aca me parece que falta paréntesis y corchetes.

y también recomiendo que agregues la implementación del algoritmo para que se muestre en consola., así el que revisa puede ver que el código corre al probarlo.

2023-06-23 01:12 UTC, rrodriguezca commented on exercises/rrodriguezca-2238/student.js
>          console.log(`${fullName}: ${average ** 2}`)
Ya revise, los corchetes y los paréntesis, están bien. El paréntesis y el corchete  se cierran en la linea 36. ¿sugieres que agregue el resultado de la compilación?

2023-06-23 01:13 UTC, rrodriguezca commented on exercises/rrodriguezca-2238/student.js
>          console.log(`${fullName}: ${average ** 2}`)
> Aca me parece que falta paréntesis y corchetes.
> 
> y también recomiendo que agregues la implementación del algoritmo para que se muestre en consola., así el que revisa puede ver que el código corre al probarlo.

Ya revise, los corchetes y los paréntesis, están bien. El paréntesis y el corchete  se cierran en la linea 36. ¿sugieres que agregue el resultado de la compilación?

2023-06-23 01:41 UTC, jorge9372 commented on exercises/rrodriguezca-2238/student.js
>          console.log(`${fullName}: ${average ** 2}`)
Oh bien, lo digo porque lo copié en mi editor y me marcaba un corchete que faltaba ...

2023-06-23 01:47 UTC, jorge9372 approved these changes

2023-06-23 01:48 UTC, jorge9372 commented on exercises/rrodriguezca-2238/student.js
>          console.log(`${fullName}: ${average ** 2}`)
Olvida lo del resultado, ya vi que llamas la función en lamlinea 43

2023-06-23 01:50 UTC, jorge9372 commented
Buen trabajo 👍

2023-06-29 15:30 UTC, mpchaneton commented
Hola! Buen trabajo! =)
## Semana 5 [EJERCICIO]
- [x]  Crea una clase Estudiante,  crea una función asíncrona calcularPromedios, calcula el promedio de las calificaciones al cuadrado de cada estudiante. Imprime el nombre completo y el promedio de calificaciones de cada estudiante utilizando Template literals.
- [x] Hacer una función que imprima los números del 1 al 10, un número cada segundo.
- [x] Hacer una función que imprima los números del 1 al 10, un número cada segundo, pero usando un ciclo for con un var.
- [x] Crear una funcionalidad que lea una lista de correos y filtre los correos validos y remueva la cadena de texto de subaddresing.
- [x] Estructura del PR
└── exercises/
    └── glrodasz-0666/
        ├── Student.js
        ├── countTo10.js
        ├── countTo10Var.js
        └── emailValidator.js

Saludos!

2023-06-29 15:31 UTC, mpchaneton approved these changes

2023-07-09 11:22 UTC, merged